FROM alpine:latest

MAINTAINER henry yang

ADD tomcat7.tar.gz /usr/local/
ADD maven3.5.tar.gz /usr/local/

RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories


RUN apk --update add curl bash openjdk8-jre-base && \
      rm -rf /var/cache/apk/*



# Set environment
ENV JAVA_HOME /usr/lib/jvm/default-jvm
ENV PATH ${PATH}:${JAVA_HOME}/bin

ENV M2_HOME /usr/local/maven3.5
ENV PATH  ${PATH}:${M2_HOME}/bin



RUN ln -s /usr/local/tomcat7/bin/catalina.sh /usr/local/bin/catalina.sh

EXPOSE 8080

ENTRYPOINT ["catalina.sh", "run" ]