# AlpineLinux open jre 8
FROM alpine:latest

# Install cURL
RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories

RUN apk --update add curl bash openjdk8-jre-base && \
      rm -rf /var/cache/apk/*

# Set environment
ENV JAVA_HOME /usr/lib/jvm/default-jvm
ENV PATH ${PATH}:${JAVA_HOME}/bin



# docker build -t henry/openjdk8:v1
#docker images   查看所有本地镜像
#docker run -d -it  --name openjdk8  henry/openjdk8:v1
#docker ps -a 获得容器id

#docker exec -it 容器id /bin/sh
